apiVersion: v1
kind: Service
metadata:
  name: keycloak2
  namespace: keycloak
  labels:
    app: keycloak2
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak2
  namespace: keycloak
  labels:
    app: keycloak2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak2
  template:
    metadata:
      labels:
        app: keycloak2
    spec:
      initContainers:
        - name: keycloak-init
          image: quay.io/keycloak/keycloak:13.0.1
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:13.0.1
        env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
